Add Spanish Documentation
LunarVim/lunarvim.org pull request #256
Opened 2022-10-16 01:28 UTC by Carlos-Carsdfj

Adding the introduction , quick start and  code.json in spanish lenguage

2022-10-16 20:22 UTC, Nojipiz commented
This is awesome! 
I will commit if this PR is accepted :D

2022-10-16 23:34 UTC, Carlos-Carsdfj commented
Thank you, as soon as I have time I will try to translate what I can.

2022-10-18 21:30 UTC, vonPB requested changes

2022-10-18 21:30 UTC, vonPB commented on i18n/es/docusaurus-plugin-content-docs/02-quick-start.md
> +Installing a [nerd font](https://www.nerdfonts.com/) is recommended. Otherwise some symbols won't be rendered properly. For more information go to the [configuration section ](./configuration/04-nerd
you probably meant to remove this :)

2022-10-18 23:32 UTC, Carlos-Carsdfj commented on i18n/es/docusaurus-plugin-content-docs/02-quick-start.md
> +Installing a [nerd font](https://www.nerdfonts.com/) is recommended. Otherwise some symbols won't be rendered properly. For more information go to the [configuration section ](./configuration/04-nerd
I'm going to change it, sorry!

2022-10-18 23:33 UTC, vonPB commented on i18n/es/docusaurus-plugin-content-docs/02-quick-start.md
> +Installing a [nerd font](https://www.nerdfonts.com/) is recommended. Otherwise some symbols won't be rendered properly. For more information go to the [configuration section ](./configuration/04-nerd
no worries at all!

2022-10-18 23:49 UTC, vonPB approved these changes

2022-10-18 23:50 UTC, merged