docs(installation): add try it first section using docker
LunarVim/lunarvim.org pull request #288
Opened 2022-11-07 06:51 UTC by cristobalgvera

Add an easy way to try the base configuration of LunarVim in a sandbox environment, allowing users to take a look at the keymappings, colorschemes, which-key setup, etc.

Personally, I find it useful to give this kind of interaction to new users.

2022-11-10 11:19 UTC, Z3rio commented
The code looks good to me at first glance. I will test this in a couple of hours when I get home :)

2022-11-10 11:20 UTC, Z3rio approved these changes

2022-11-10 22:41 UTC, vonPB commented
As far as I know you can install lvim next to your own nvim -> without changing your normal config at all.
@kylo252 probably has a better understanding of this.
I think there was some discussion about pointing that out in the docs already.

Otherwise, never worked with docker, but looks alright :)

2022-11-11 02:04 UTC, Nojipiz commented
I think is a cool feature, it's true that you can install lvim next to your own nvim, but it will require to _"foul the system"_ with another installation, docker provides predictable and isolated environment. Please give it a try!

2022-11-11 02:23 UTC, vonPB requested changes
Got a few problems with hyper-v on my machine, so cant test it ;/
I'm happy to merge this if someone can confirm it works.

Also feel like the code block is a bit lengthy/blocking. Would be nice if we could wrap it in something like the [detail container from vuepress](https://vuepress.vuejs.org/guide/markdown.html#custom-containers). Couldn't find one in Docusaurus. Happy to write on another day...

2022-11-11 07:00 UTC, kylo252 commented
could you guys update the dockerfile in the main repo and link to it here instead?

it could even be a new installation method.

2022-11-11 19:38 UTC, cristobalgvera commented on docs/01-installation.md
> +If your are using Docker in your machine, you can run the following command to try LunarVim while keeping your existing Neovim configuration intact.
I rephrase the detail, let me know how it looks!

2022-11-11 19:43 UTC, cristobalgvera commented
> Also feel like the code block is a bit lengthy/blocking. Would be nice if we could wrap it in something like the [detail container from vuepress](https://vuepress.vuejs.org/guide/markdown.html#custom-containers). Couldn't find one in Docusaurus. Happy to write on another day...

Yeah, seems like Docusaurus doesn't provide it :( do you have any other idea about how to present it?

2022-11-11 19:50 UTC, vonPB commented
as kylo said, we can update (or add a new one) the docker file in [lunarvim](https://github.com/LunarVim/LunarVim/blob/master/utils/docker/Dockerfile.remote). After that we could just have a one liner to run the "Try it first". That would be small enough for my taste :)

@cristobalgvera can you try if the docker file works as u expect and let me know? I'll update the file to get either `rolling` or `release-1.2/neovim-0.8` instead of the old `rolling` in a sec.

2022-11-11 19:50 UTC, vonPB commented
new text looks good! Ty

2022-11-11 19:59 UTC, vonPB commented
https://github.com/LunarVim/LunarVim/blob/update_docker/utils/docker/Dockerfile.remote
leaving the change here for now. I'll merge it after your feedback if it works :)

2022-11-18 16:56 UTC, LostNeophyte commented
> https://github.com/LunarVim/LunarVim/blob/update_docker/utils/docker/Dockerfile.remote leaving the change here for now. I'll merge it after your feedback if it works :)

It does work, tested in podman

2022-11-25 13:56 UTC, kylo252 commented
we should add it as a new tab btw

![image](https://user-images.githubusercontent.com/59826753/204000249-a97130c5-937a-4504-bd42-c7a8c75a23e0.png)

2022-12-13 19:18 UTC, cristobalgvera commented
Guys, I don't know how to continue, what should I do?

Thanks!

2022-12-13 19:25 UTC, vonPB commented
@cristobalgvera  since https://github.com/LunarVim/LunarVim/blob/master/utils/docker/Dockerfile.remote is basically doing what you initially wrote, it would make sense to just add a command to the docs that gets this file and executes it (similar to the installation command). This wouldn't be taking up as much space as your initial proposal did and we could just add it as a tab here:
![image](https://user-images.githubusercontent.com/65032978/207426006-18e1057f-00c4-425d-b07f-89f18954a0a3.png)
with something like "Try it first in docker!"

2022-12-13 19:26 UTC, vonPB commented
Thanks for not abandoning this :)!

2022-12-13 21:55 UTC, cristobalgvera commented
> @cristobalgvera since https://github.com/LunarVim/LunarVim/blob/master/utils/docker/Dockerfile.remote is basically doing what you initially wrote, it would make sense to just add a command to the docs that gets this file and executes it (similar to the installation command). This wouldn't be taking up as much space as your initial proposal did and we could just add it as a tab here: ![image](https://user-images.githubusercontent.com/65032978/207426006-18e1057f-00c4-425d-b07f-89f18954a0a3.png) with something like "Try it first in docker!"

Here is the result 😁

<img width="839" alt="image" src="https://user-images.githubusercontent.com/60797050/207452137-2cd5eda2-c882-4f8d-9429-2de5006f7e54.png">

2022-12-13 22:02 UTC, vonPB commented
@cristobalgvera  looks great!
Can you maybe remove the line breaks?  A one liner would look in my opinion.
![image](https://user-images.githubusercontent.com/65032978/207453228-5dc19765-1c20-408a-a1c4-18f28a88a697.png)

Happy to merge otherwise :)

2022-12-13 22:09 UTC, vonPB approved these changes

2022-12-13 22:10 UTC, merged